//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binder.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTaskForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTaskForm() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Binder.Properties.Languages.ResourceTaskForm", typeof(ResourceTaskForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select category for this task. Useful for organizing many tasks, separating them by field..
        /// </summary>
        internal static string CategoryHelpText {
            get {
                return ResourceManager.GetString("CategoryHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose category for task:.
        /// </summary>
        internal static string CategoryListLabelText {
            get {
                return ResourceManager.GetString("CategoryListLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is it completed task?.
        /// </summary>
        internal static string CompleteCheckBoxText {
            get {
                return ResourceManager.GetString("CompleteCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This option allows you to make task completed. Use to end task and for archive creation..
        /// </summary>
        internal static string CompleteHelpText {
            get {
                return ResourceManager.GetString("CompleteHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Describe your task here. Use this field for task&apos;s details rather than Name filed..
        /// </summary>
        internal static string DescriptionHelpText {
            get {
                return ResourceManager.GetString("DescriptionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Describe the task (optional):.
        /// </summary>
        internal static string DescriptionLabelText {
            get {
                return ResourceManager.GetString("DescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accept.
        /// </summary>
        internal static string DialogAcceptButtonText {
            get {
                return ResourceManager.GetString("DialogAcceptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        internal static string DialogCancelButtonText {
            get {
                return ResourceManager.GetString("DialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Set end date and time. That&apos;s deadline for this task..
        /// </summary>
        internal static string EndDateHelpText {
            get {
                return ResourceManager.GetString("EndDateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task end:.
        /// </summary>
        internal static string EndDateLabelText {
            get {
                return ResourceManager.GetString("EndDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Binder - Add New Task.
        /// </summary>
        internal static string FormTitleAddition {
            get {
                return ResourceManager.GetString("FormTitleAddition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Binder - Edit Task - {0}.
        /// </summary>
        internal static string FormTitleEdit {
            get {
                return ResourceManager.GetString("FormTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Help.
        /// </summary>
        internal static string HelpBoxText {
            get {
                return ResourceManager.GetString("HelpBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name your task as simply as possible. One word will be easier to remember..
        /// </summary>
        internal static string NameHelpText {
            get {
                return ResourceManager.GetString("NameHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name the new task:.
        /// </summary>
        internal static string NameLabelText {
            get {
                return ResourceManager.GetString("NameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No category.
        /// </summary>
        internal static string NoCategoryComboBoxText {
            get {
                return ResourceManager.GetString("NoCategoryComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu If this option is enabled, Binder will take current date and time as creation point and will not set deadline. Useful for tasks, that doesn&apos;t have date to finish. Disable to change these data..
        /// </summary>
        internal static string NoDateHelpText {
            get {
                return ResourceManager.GetString("NoDateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No date for this task.
        /// </summary>
        internal static string NoDateTaskText {
            get {
                return ResourceManager.GetString("NoDateTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Set start date and time. It can be useful in archive. If you don&apos;t create archive task, don&apos;t change it and let Binder set it for you..
        /// </summary>
        internal static string StartDateHelpText {
            get {
                return ResourceManager.GetString("StartDateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task start:.
        /// </summary>
        internal static string StartDateLabelText {
            get {
                return ResourceManager.GetString("StartDateLabelText", resourceCulture);
            }
        }
    }
}
