//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binder.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMainForm() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Binder.Properties.Languages.ResourceMainForm", typeof(ResourceMainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu About App.
        /// </summary>
        internal static string AboutAppOptionText {
            get {
                return ResourceManager.GetString("AboutAppOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Task.
        /// </summary>
        internal static string AddTaskOptionText {
            get {
                return ResourceManager.GetString("AddTaskOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All data saved to storage..
        /// </summary>
        internal static string AllDataSavedLabelText {
            get {
                return ResourceManager.GetString("AllDataSavedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manager.
        /// </summary>
        internal static string CategoryManagerMenuText {
            get {
                return ResourceManager.GetString("CategoryManagerMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data.
        /// </summary>
        internal static string DataManagerMenuText {
            get {
                return ResourceManager.GetString("DataManagerMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data from {0} saved to storage..
        /// </summary>
        internal static string DataSavedLabelText {
            get {
                return ResourceManager.GetString("DataSavedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete Category.
        /// </summary>
        internal static string DeleteCategoryOptionText {
            get {
                return ResourceManager.GetString("DeleteCategoryOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete Task.
        /// </summary>
        internal static string DeleteTaskOptionText {
            get {
                return ResourceManager.GetString("DeleteTaskOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description.
        /// </summary>
        internal static string DescriptionColumnText {
            get {
                return ResourceManager.GetString("DescriptionColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit Task.
        /// </summary>
        internal static string EditTaskOptionText {
            get {
                return ResourceManager.GetString("EditTaskOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deadline.
        /// </summary>
        internal static string EndDateColumnText {
            get {
                return ResourceManager.GetString("EndDateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exit.
        /// </summary>
        internal static string ExitOptionText {
            get {
                return ResourceManager.GetString("ExitOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Binder.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Help.
        /// </summary>
        internal static string MiscMenuText {
            get {
                return ResourceManager.GetString("MiscMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        internal static string NameColumnText {
            get {
                return ResourceManager.GetString("NameColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Category.
        /// </summary>
        internal static string NewCategoryOptionText {
            get {
                return ResourceManager.GetString("NewCategoryOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu None.
        /// </summary>
        internal static string NoDeadlineDisplayText {
            get {
                return ResourceManager.GetString("NoDeadlineDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save All.
        /// </summary>
        internal static string SaveAllOptionText {
            get {
                return ResourceManager.GetString("SaveAllOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        internal static string SaveOptionText {
            get {
                return ResourceManager.GetString("SaveOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string SettingsOptionText {
            get {
                return ResourceManager.GetString("SettingsOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show/Hide Complete Tasks.
        /// </summary>
        internal static string ShowHideCompleteTaskListText {
            get {
                return ResourceManager.GetString("ShowHideCompleteTaskListText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start Date.
        /// </summary>
        internal static string StartDateColumnText {
            get {
                return ResourceManager.GetString("StartDateColumnText", resourceCulture);
            }
        }
    }
}
