//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binder.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Binder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category with this name already exists..
        /// </summary>
        internal static string CategoryAlreadyExistsErrorMessage {
            get {
                return ResourceManager.GetString("CategoryAlreadyExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please provide name for new category:.
        /// </summary>
        internal static string CategoryNameInputDialogText {
            get {
                return ResourceManager.GetString("CategoryNameInputDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Completed.
        /// </summary>
        internal static string CompletedTaskListText {
            get {
                return ResourceManager.GetString("CompletedTaskListText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete selected category?.
        /// </summary>
        internal static string ConfirmCategoryDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmCategoryDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to exit Binder? Unsaved data will be lost..
        /// </summary>
        internal static string ConfirmProgramExit {
            get {
                return ResourceManager.GetString("ConfirmProgramExit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete selected task on current category?.
        /// </summary>
        internal static string ConfirmTaskDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmTaskDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Binder v{0}  - Strayker Software Development Build - Use only for dev operations.
        /// </summary>
        internal static string DebugBuildMessage {
            get {
                return ResourceManager.GetString("DebugBuildMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Default.
        /// </summary>
        internal static string DefaultTaskCategoryName {
            get {
                return ResourceManager.GetString("DefaultTaskCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This category can&apos;t be deleted..
        /// </summary>
        internal static string DeleteSpecialListErrorText {
            get {
                return ResourceManager.GetString("DeleteSpecialListErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nothing was changed. Edition aborted..
        /// </summary>
        internal static string EditedTaskStillTheSameErrorMessage {
            get {
                return ResourceManager.GetString("EditedTaskStillTheSameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Saving to file storage in Binder is not supporting single category saving, to save computer&apos;s disks liveliness..
        /// </summary>
        internal static string FileStorageNotSupportingSingleSaveMessage {
            get {
                return ResourceManager.GetString("FileStorageNotSupportingSingleSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is no category in database named {0} for task {1}. This task will not be loaded by Binder. Please verify task&apos;s category name in storage or add new category via Binder..
        /// </summary>
        internal static string NoCategoryFoundErrorMessage {
            get {
                return ResourceManager.GetString("NoCategoryFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No data provided..
        /// </summary>
        internal static string NoDataProvidedErrorText {
            get {
                return ResourceManager.GetString("NoDataProvidedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a row..
        /// </summary>
        internal static string NoRowSelectedErrorMessage {
            get {
                return ResourceManager.GetString("NoRowSelectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please provide new name for selected category:.
        /// </summary>
        internal static string RenameCategoryDialogText {
            get {
                return ResourceManager.GetString("RenameCategoryDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This category can&apos;t be renamed..
        /// </summary>
        internal static string RenameSpecialListErrorText {
            get {
                return ResourceManager.GetString("RenameSpecialListErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This task already exists in {0} category..
        /// </summary>
        internal static string TaskAlreadyExistsErrorMessage {
            get {
                return ResourceManager.GetString("TaskAlreadyExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unknown exception: {0}.
        /// </summary>
        internal static string UnknownExceptionMessage {
            get {
                return ResourceManager.GetString("UnknownExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This function is not enabled in current version of Binder. Work in progress..
        /// </summary>
        internal static string WorkInProgressMessage {
            get {
                return ResourceManager.GetString("WorkInProgressMessage", resourceCulture);
            }
        }
    }
}
