/**
 * Binder API
 * ASP.NET Core Web API backend app for Binder Solution
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TaskShow = 0 | 1 | 2 | 3;

export const TaskShow = {
    NUMBER_0: 0 as TaskShow,
    NUMBER_1: 1 as TaskShow,
    NUMBER_2: 2 as TaskShow,
    NUMBER_3: 3 as TaskShow
};

